CU-mz87nx: unit tests for maker-otc matching market
nayms/contracts pull request #101
Opened 2021-06-29 10:58 UTC by najienka

2021-06-29 10:58 UTC, melks commented
Task linked: [CU-mz87nx Write functional tests for existing MakerOTC Matching market](https://app.clickup.com/t/mz87nx)

2021-07-07 18:35 UTC, hiddentao requested changes
Looking good.

However I've noticed that test cases have a dependency on each other. This makes the test suite unnecessarily fragile, since changing a single test case will require consideration of how it impacts other test cases.

In our existing test suite all test cases are independent of each other - we make use of ganache's snapshot capability (example)[https://github.com/nayms/contracts/blob/master/test/policyClaims.js#L273-L279] as well as nested `describe()` blocks to progressively setup test data as needed (example)[https://github.com/nayms/contracts/blob/master/test/policyClaims.js#L746].

Please refactor the test suite in this manner so that test cases are independent.

2021-07-13 12:16 UTC, hiddentao requested changes
Looking good!

2021-07-13 12:16 UTC, hiddentao commented on test/matchingMarket.js
> +        it('should not match all three prior offers if the prices do not match', async () => {
match all three?

2021-07-13 12:16 UTC, hiddentao commented on test/matchingMarket.js
> +        })
Pls add a final account balance check

2021-07-13 12:16 UTC, hiddentao commented on test/matchingMarket.js
> +        })
Pls add a final account balance check

2021-07-13 12:16 UTC, hiddentao commented on test/matchingMarket.js
> +        })
Pls add a final account balance check

2021-07-13 12:58 UTC, najienka commented on test/matchingMarket.js
> +        })
resolved

2021-07-13 13:01 UTC, najienka commented on test/matchingMarket.js
> +        })
resolved

2021-07-13 13:05 UTC, najienka commented on test/matchingMarket.js
> +        })
resolved

2021-07-13 13:08 UTC, najienka commented on test/matchingMarket.js
> +        it('should not match all three prior offers if the prices do not match', async () => {
typo. Apologies

2021-07-13 14:05 UTC, najienka commented on test/matchingMarket.js
> +            await matchingMarketInstance.sellAllAmount(erc20WETH.address, toBN(15e18), erc20DAI.address, toBN(30e18), {from: accounts[1]}).should.be.rejectedWith('revert')
resolved

2021-07-14 09:55 UTC, hiddentao commented on package.json
> +    "@openzeppelin/test-helpers": "^0.5.11",
is this still used?

2021-07-14 09:56 UTC, najienka commented on package.json
> +    "@openzeppelin/test-helpers": "^0.5.11",
Thanks for spotting this!

2021-07-16 10:14 UTC, najienka commented
Unit tests for policy are failing in this PR build but passing in master branch. Code has been merged in a new branch for new PR.

Closing PR.

2021-07-16 10:14 UTC, najienka commented
Unit tests for policy are failing in this PR build but passing in master branch. Code has been merged in a new branch for new PR.

Closing PR.

2021-07-16 10:14 UTC, closed without merging