New markets tests
nayms/contracts pull request #108
Opened 2021-07-16 11:14 UTC by najienka

2021-07-18 22:28 UTC, hiddentao commented on test/newMatchingMarket.js
> +    describe('can match a pair of matching offers', () => {
Are these disabled because they still need to be fixed?

2021-07-19 21:43 UTC, melks commented
Task linked: [CU-nzfzn8 Link matching markets tests to new market smart contracts](https://app.clickup.com/t/nzfzn8)

2021-07-20 08:31 UTC, hiddentao requested changes
Mostly good, I think tests for handling trade notifications are missing, and then there are some other minor changes needed.

2021-07-20 08:31 UTC, hiddentao commented on test/newMatchingMarket.js
> +    /* before(async () => {
Pls remove

2021-07-20 08:31 UTC, hiddentao commented on test/newMatchingMarket.js
> +        it('should match offers fully, return the fill amount for a token pair, with pay amount and minimum fill amount', async () => {
Minor point: this test title needs updating

2021-07-20 08:31 UTC, hiddentao commented on test/newMatchingMarket.js
> +    describe('handleTrade and handleClosure should handle trade or closure or cancellation notifications in market observer', () => {
`orderType.trade` never seems to be checked for in any of the tests?

2021-07-20 08:31 UTC, hiddentao commented on contracts/DummyMarketObserver.sol
> +pragma solidity 0.6.12;
Pls move file into `contracts/test`

2021-07-20 08:31 UTC, hiddentao commented on contracts/base/IDummyMarketObserver.sol
> +pragma solidity 0.6.12;
Pls move file into `contracts/test`

2021-07-20 08:31 UTC, hiddentao commented on test/newMatchingMarket.js
> +        it('should match offers partly, return the fill amount for a token pair, with pay amount and minimum fill amount', async () => {
Title needs updating since there is no longer a minimum fill amount specified

2021-07-20 08:31 UTC, hiddentao commented on test/newMatchingMarket.js
> +    describe('can match multiple or more than two matching offers simoultaneously', () => {
`simultaneously`

2021-07-20 08:31 UTC, hiddentao commented on test/newMatchingMarket.js
> +        it('should not match the two created offers if the prices do not match', async () => {
Don't need this test

2021-07-20 08:31 UTC, hiddentao commented on test/newMatchingMarket.js
> +        it('get correct last offer id after creating offers', async () => {
Don't need this test

2021-07-21 12:51 UTC, hiddentao commented on contracts/base/IDummyMarketObserver.sol
> +pragma solidity 0.6.12;
This has not been resolved

2021-07-21 12:55 UTC, najienka commented on contracts/base/IDummyMarketObserver.sol
> +pragma solidity 0.6.12;
apologies, done now.

2021-07-21 18:36 UTC, hiddentao approved these changes

2021-07-22 06:33 UTC, merged